cortxcontrol:
  name: cortx-control
  image: ghcr.io/seagate/centos:7
  secretinfo: secret-info.txt
  serviceaccountname: cortx
  service:
    loadbal:
      enabled: true
      name: cortx-control-loadbal-svc
      type: NodePort
      ports:
        https: 8081
      nodePorts:
        https: ""
  cfgmap:
    mountpath: /etc/cortx/solution
    name: cortx
    volmountname: config001
  sslcfgmap:
    mountpath: /etc/cortx/solution/ssl
    volmountname: ssl-config001
    name: cortx-ssl-cert
  machineid:
    mountpath: /etc/cortx/solution/node
    value: ""
  localpathpvc:
    name: cortx-fs-local-pvc
    mountpath: /etc/cortx # This is the mount path in the container
    requeststoragesize: 1Gi
