namespace: default
cortxcontrol:
  name: cortx-control
  image: ghcr.io/seagate/centos:7
  secretinfo: secret-info.txt
  serviceaccountname: cortx-sa
  service:
    clusterip:
      name: cortx-control-clusterip-svc
      type: ClusterIP
    headless:
      name: cortx-control-headless-svc
    loadbal:
      name: cortx-control-loadbal-svc
      type: LoadBalancer
  cfgmap:
    mountpath: /etc/cortx/solution
    name: cortx-control-cfgmap001
    volmountname: config001
  sslcfgmap:
    mountpath: /etc/cortx/solution/ssl
    volmountname: ssl-config001
    name: cortx-ssl-cert-cfgmap
  machineid:
    mountpath: /etc/cortx/solution/node
    volmountname: machine-id-config
    name:  cortx-control-machine-id-cfgmap
    value: ""
  localpathpvc:
    name: cortx-fs-local-pvc
    mountpath: /etc/cortx # This is the mount path in the container
    requeststoragesize: 1Gi
  resource_allocation:
    setup:
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
    motr_fsm:
      resources:
        requests:
          cpu: 125m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 128Mi
    utils_message:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi 
    bgscheduler:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    csm_agent:
      resources:
        requests:
          cpu: 125m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 512Mi
