namespace: default
cortxcontrol:
  name: cortx-control
  image: ghcr.io/seagate/centos:7
  secretinfo: secret-info.txt
  serviceaccountname: cortx-sa
  service:
    clusterip:
      name: cortx-control-clusterip-svc
      type: ClusterIP
    headless:
      name: cortx-control-headless-svc
    loadbal:
      name: cortx-control-loadbal-svc
      type: LoadBalancer
  cfgmap:
    mountpath: /etc/cortx/solution
    name: cortx-control-cfgmap001
    volmountname: config001
  sslcfgmap:
    mountpath: /etc/cortx/solution/ssl
    volmountname: ssl-config001
    name: cortx-ssl-cert-cfgmap
  machineid:
    mountpath: /etc/cortx/solution/node
    volmountname: machine-id-config
    name:  cortx-control-machine-id-cfgmap
    value: ""
  localpathpvc:
    name: cortx-fs-local-pvc
    mountpath: /etc/cortx # This is the mount path in the container
    requeststoragesize: 1Gi
  resource_allocation:
    capacity_monitor:
      resources:
        requests:
          cpu: 125m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 128Mi
    ## TODO: Add message service resources to the solution.yaml, solution_dummy.yaml, ##
    ## and solution-check.yaml and update cortx-control-pod.yaml                      ##
    # message_service:
    #   resources:
    #     requests:
    #       cpu: 
    #       memory: 
    #     limits:
    #       cpu: 
    #       memory: 
    s3_bg_workers:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    mgmt_service:
      resources:
        requests:
          cpu: 125m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 512Mi
