cluster:
  name: cortx-cluster
  id: <<.Values.cortx.cluster.id>>
  node_types:
  - name: data_node
    components:
      - name: utils
      - name: motr
        services:
          - io
      - name: hare
    storage:
    <<.Values.cluster.storage_list>>
  storage_sets:
  - name: <<.Values.cluster.storage_sets.name>>
    durability:
      sns: <<.Values.cluster.storage_sets.durability.sns>>
      dix: <<.Values.cluster.storage_sets.durability.dix>>
    nodes:
    <<.Values.cluster.storage_sets.nodes>>
