apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxcontrol.service.clusterip.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.cortxcontrol.service.clusterip.type }}
  selector:
    app: {{ .Values.cortxcontrol.name }}
  ports:
    - name: cortx-csm-agent-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxcontrol.service.headless.name }}
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ .Values.cortxcontrol.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxcontrol.service.loadbal.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.cortxcontrol.service.loadbal.type }}
  selector:
    app: {{ .Values.cortxcontrol.name }}
  ports:
  - name: cotrx-control-8081
    port: 8081
    targetPort: 8081
    nodePort: 31169