apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.cortxcontrol.name }}
  name: {{ .Values.cortxcontrol.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cortxcontrol.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cortxcontrol.name }}
    spec:
      hostname: {{ .Values.cortxcontrol.service.headless.name }}
      serviceAccountName: {{ .Values.cortxcontrol.serviceaccountname }}
      volumes:
        - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxcontrol.cfgmap.name }}
        - name: {{ .Values.cortxcontrol.sslcfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxcontrol.sslcfgmap.name }}
        - name: {{ .Values.cortxcontrol.machineid.volmountname }}
          configMap:
            name: {{ .Values.cortxcontrol.machineid.name }}
        - name: local-path-pv
          persistentVolumeClaim:
            claimName: {{ .Values.cortxcontrol.localpathpvc.name }}
        {{- range .Files.Lines .Values.cortxcontrol.secretinfo }}
        - name: {{ printf "%s" . }}
          secret:
            secretName: {{ printf "%s" . }}
        {{- end }}
      initContainers:
      - name: cortx-setup
        image: {{ .Values.cortxcontrol.image }}
        imagePullPolicy: IfNotPresent        
        command: 
          - /bin/sh
        {{- if eq .Values.cortxcontrol.image "centos:7" }}
        args: 
          - -c
          - sleep $(shuf -i 5-10 -n 1)s
        {{- else }}
        args: 
          - -c
          - /opt/seagate/cortx/provisioner/bin/cortx_deploy -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf ;
        {{- end }}
        volumeMounts:
          - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
            mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
          - name: {{ .Values.cortxcontrol.sslcfgmap.volmountname }}
            mountPath: {{ .Values.cortxcontrol.sslcfgmap.mountpath }}
          - name: {{ .Values.cortxcontrol.machineid.volmountname }}
            mountPath: {{ .Values.cortxcontrol.machineid.mountpath }}
          - name: {{ .Values.cortxgluster.pv.name }}
            mountPath: {{ .Values.cortxgluster.pv.mountpath }}
          - name: local-path-pv
            mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
          {{- range .Files.Lines .Values.cortxcontrol.secretinfo }}
          - name: {{ printf "%s" . }}
            mountPath: /etc/cortx/solution/secret
            readOnly: true
          {{- end }}
        ports:
        - containerPort: 5050
      containers:
        - name: cortx-free-space-monitor
          image: {{ .Values.cortxcontrol.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxcontrol.image "ghcr.io/seagate/centos:7" }}      
          command: ["/bin/sleep", "3650d"]
          {{- else }}     
          command: ["/bin/sleep", "3650d"]
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
            - name: {{ .Values.cortxcontrol.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.sslcfgmap.mountpath }}
            - name: {{ .Values.cortxcontrol.machineid.volmountname }}
              mountPath: {{ .Values.cortxcontrol.machineid.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
            {{- range .Files.Lines .Values.cortxcontrol.secretinfo }}
            - name: {{ printf "%s" . }}
              mountPath: /etc/cortx/solution/secret
              readOnly: true
            {{- end }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxcontrol.name }}
          securityContext:
            allowPrivilegeEscalation: false
        - name: cortx-fsm-motr
          image: {{ .Values.cortxcontrol.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxcontrol.image "ghcr.io/seagate/centos:7" }}          
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command: 
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/motr/bin/motr_setup start --services fsm --config yaml:///etc/cortx/cluster.conf;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
            - name: {{ .Values.cortxcontrol.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.sslcfgmap.mountpath }}
            - name: {{ .Values.cortxcontrol.machineid.volmountname }}
              mountPath: {{ .Values.cortxcontrol.machineid.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
            {{- range .Files.Lines .Values.cortxcontrol.secretinfo }}
            - name: {{ printf "%s" . }}
              mountPath: /etc/cortx/solution/secret
              readOnly: true
            {{- end }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxcontrol.name }}
          securityContext:
            allowPrivilegeEscalation: false
        - name: cortx-bg-producer
          image: {{ .Values.cortxcontrol.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxcontrol.image "ghcr.io/seagate/centos:7" }}          
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command: 
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/s3/bin/s3_start --service s3bgproducer -c yaml:///etc/cortx/cluster.conf;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
            - name: {{ .Values.cortxcontrol.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.sslcfgmap.mountpath }}
            - name: {{ .Values.cortxcontrol.machineid.volmountname }}
              mountPath: {{ .Values.cortxcontrol.machineid.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
            {{- range .Files.Lines .Values.cortxcontrol.secretinfo }}
            - name: {{ printf "%s" . }}
              mountPath: /etc/cortx/solution/secret
              readOnly: true
            {{- end }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxcontrol.name }}
          securityContext:
            allowPrivilegeEscalation: false
        - name: cortx-csm-agent
          image: {{ .Values.cortxcontrol.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxcontrol.image "ghcr.io/seagate/centos:7" }}          
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command: 
            - /bin/sh
          args:
            - -c
            - /usr/bin/csm_agent start -c yaml:///etc/cortx/cluster.conf;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
            - name: {{ .Values.cortxcontrol.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.sslcfgmap.mountpath }}
            - name: {{ .Values.cortxcontrol.machineid.volmountname }}
              mountPath: {{ .Values.cortxcontrol.machineid.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
            {{- range .Files.Lines .Values.cortxcontrol.secretinfo }}
            - name: {{ printf "%s" . }}
              mountPath: /etc/cortx/solution/secret
              readOnly: true
            {{- end }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxcontrol.name }}
          ports:
          - containerPort: 8081
          securityContext:
            allowPrivilegeEscalation: false
