apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.cortxcontrol.name }}
  name: {{ .Values.cortxcontrol.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cortxcontrol.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cortxcontrol.name }}
        name: cortx-control
        {{- if .Values.cortxcontrol.machineid.value }}
        cortx.io/machine-id: {{ .Values.cortxcontrol.machineid.value }}
        {{- end }}
        cortx.io/service-type: cortx-control
    spec:
      hostname: {{ .Values.cortxcontrol.name }}
      serviceAccountName: {{ .Values.cortxcontrol.serviceaccountname }}
      volumes:
        - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxcontrol.cfgmap.name }}
        - name: {{ .Values.cortxcontrol.sslcfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxcontrol.sslcfgmap.name }}
        - name: {{ .Values.cortxcontrol.machineid.volmountname }}
          configMap:
            name: {{ .Values.cortxcontrol.machineid.name }}
        {{- if .Values.cortxcontrol.machineid.value }}
        - name: machine-id
          downwardAPI:
            items:
              - path: "id"
                fieldRef:
                  fieldPath: metadata.labels['cortx.io/machine-id']
        {{- end }}
        - name: local-path-pv
          persistentVolumeClaim:
            claimName: {{ .Values.cortxcontrol.localpathpvc.name }}
        {{- range .Files.Lines .Values.cortxcontrol.secretinfo }}
        - name: {{ printf "%s" . }}
          secret:
            secretName: {{ printf "%s" . }}
        {{- end }}
      initContainers:
      - name: cortx-setup
        image: {{ .Values.cortxcontrol.image }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
        {{- if eq .Values.cortxcontrol.image "ghcr.io/seagate/centos:7" }}
        args:
          - -c
          - sleep $(shuf -i 5-10 -n 1)s
        {{- else }}
        args:
          - -c
          {{- if .Values.cortxcontrol.machineid.value }}
          - /opt/seagate/cortx/provisioner/bin/cortx_deploy -n $MACHINE_ID -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf;
          {{- else }}
          - /opt/seagate/cortx/provisioner/bin/cortx_deploy -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf;
          {{- end }}
        {{- end }}
        volumeMounts:
          - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
            mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
          - name: {{ .Values.cortxcontrol.sslcfgmap.volmountname }}
            mountPath: {{ .Values.cortxcontrol.sslcfgmap.mountpath }}
          {{- if .Values.cortxcontrol.machineid.value }}
          - name: machine-id
            mountPath: {{ .Values.cortxcontrol.machineid.mountpath }}
          {{- end }}
          - name: local-path-pv
            mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
          {{- range .Files.Lines .Values.cortxcontrol.secretinfo }}
          - name: {{ printf "%s" . }}
            mountPath: /etc/cortx/solution/secret
            readOnly: true
          {{- end }}
        env:
          - name: MACHINE_ID
            value: {{ printf "%s" .Values.cortxcontrol.machineid.value | quote }}
        ports:
        - containerPort: 5050
      containers:
        - name: cortx-csm-agent
          image: {{ .Values.cortxcontrol.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxcontrol.image "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command: 
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/csm/bin/csm_agent start -c yaml:///etc/cortx/cluster.conf;
              sleep infinity;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxcontrol.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.cfgmap.mountpath }}
            - name: {{ .Values.cortxcontrol.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxcontrol.sslcfgmap.mountpath }}
            {{- if .Values.cortxcontrol.machineid.value }}
            - name: machine-id
              mountPath: {{ .Values.cortxcontrol.machineid.mountpath }}
            {{- end }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxcontrol.localpathpvc.mountpath }}
            {{- range .Files.Lines .Values.cortxcontrol.secretinfo }}
            - name: {{ printf "%s" . }}
              mountPath: /etc/cortx/solution/secret
              readOnly: true
            {{- end }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxcontrol.name }}
          ports:
          - containerPort: 8081
          securityContext:
            allowPrivilegeEscalation: false
