apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxcontrol.service.loadbal.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.cortxcontrol.service.loadbal.type }}
  selector:
    app: {{ .Values.cortxcontrol.name }}
  ports:
  - name: cotrx-control-8081
    port: 8081
    targetPort: 8081
    nodePort: 31169
