apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: server
    cortx.io/service-type:  {{ .Values.cortxserver.serviceType }}
  name: cortx-server
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  serviceName: {{ .Values.cortxserver.service.headless.name }}
  replicas: {{ .Values.cortxserver.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      cortx.io/service-type: cortx-server
      cortx.io/hax-enabled: "true"
      cortx.io/service-domain: "{{ .Values.cortxserver.service.headless.name }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterdomain }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        ### TODO k8s Label 'name: cortx-server' is deprecated in favor of 'cortx.io/service-type: cortx-server'
        name: cortx-server
        cortx.io/service-type: cortx-server
        cortx.io/hax-enabled: "true"
        cortx.io/service-domain: "{{ .Values.cortxserver.service.headless.name }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterdomain }}"
    spec:
      subdomain: {{ .Values.cortxserver.service.headless.name }}
      serviceAccountName: {{ .Values.cortxserver.serviceaccountname }}
      volumes:
        - name: {{ .Values.cortxserver.cfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxserver.cfgmap.name }}
        - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxserver.sslcfgmap.name }}
        - name: {{ .Values.cortxserver.secretname }}
          secret:
            secretName: {{ .Values.cortxserver.secretname }}
      initContainers:
      - name: cortx-setup
        image: {{ .Values.cortxserver.image }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
        args:
          - -c
          {{- if eq .Values.cortxserver.image "ghcr.io/seagate/centos:7" }}
          - sleep $(shuf -i 5-10 -n 1)s
          {{- else }}
          - /opt/seagate/cortx/provisioner/bin/cortx_deploy -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf;
          {{- end }}
        volumeMounts:
          - name: {{ .Values.cortxserver.cfgmap.volmountname }}
            mountPath: {{ .Values.cortxserver.cfgmap.mountpath }}
          - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
            mountPath: {{ .Values.cortxserver.sslcfgmap.mountpath }}
          - name: data
            mountPath: {{ .Values.cortxserver.localpathpvc.mountpath }}
          - name: {{ .Values.cortxserver.secretname }}
            mountPath: /etc/cortx/solution/secret
            readOnly: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
        - containerPort: 5050
      containers:
        - name: cortx-rgw
          image: {{ .Values.cortxserver.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxserver.image  "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command:
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/rgw/bin/rgw_setup start -c yaml:///etc/cortx/cluster.conf;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxserver.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.cfgmap.mountpath }}
            - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.sslcfgmap.mountpath }}
            - name: data
              mountPath: {{ .Values.cortxserver.localpathpvc.mountpath }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          ports:
          - name: rgw-http
            containerPort: 22751
            protocol: TCP
          - name: rgw-https
            containerPort: 23001
            protocol: TCP
          {{- if .Values.cortxserver.rgw.resources }}
          resources: {{- toYaml .Values.cortxserver.rgw.resources | nindent 12 }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
        - name: cortx-hax
          image: {{ .Values.cortxserver.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxserver.image  "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command:
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/hare/bin/hare_setup start --config yaml:///etc/cortx/cluster.conf;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxserver.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.cfgmap.mountpath }}
            - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.sslcfgmap.mountpath }}
            - name: data
              mountPath: {{ .Values.cortxserver.localpathpvc.mountpath }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          ports:
          - name: hax
            containerPort: {{ .Values.cortxserver.hax.port | int }}
            protocol: TCP
          {{- if .Values.cortxserver.hax.resources }}
          resources: {{- toYaml .Values.cortxserver.hax.resources | nindent 12 }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: {{- toYaml .Values.cortxserver.localpathpvc.accessmodes | nindent 6 }}
      storageClassName: {{ .Values.cortxserver.localpathpvc.storageclass }}
      resources:
        requests:
          storage: {{ .Values.cortxserver.localpathpvc.requeststoragesize }}
