apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxclient.service.headless.name }}
  namespace: {{ .Release.Namespace }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ .Values.cortxclient.name }}
