{{- if .Values.ha.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cortx.ha.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
  labels: {{- include "cortx.labels" . | nindent 4 }}
    app.kubernetes.io/component: ha
{{- end }}
