blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/Seagate/cortx-k8s/discussions
    about: Want to suggest an idea? Start a new discussion.
  - name: Community Support
    url: https://github.com/Seagate/cortx-k8s/discussions
    about: Ask a question or request general support on the Discussion forum.
