blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/Seagate/cortx/issues/new/choose
    about: Want to suggest an idea? Visit the main CORTX project and create a feature request.
  - name: CORTX on Kubernetes Questions and Support
    url: https://github.com/Seagate/cortx-k8s/discussions
    about: Have questions or need support for CORTX on Kubernetes for anything that isn't a bug report? Go ahead and start a new discussion.
  - name: CORTX Community Support
    url: https://cortx.link/slack_invite
    about: Join us on Slack for general CORTX questions and support.
