{{- if .Values.platform.services.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortx.fullname" . }}-hax
  namespace: {{ .Release.Namespace }}
  labels: {{ include "cortx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.platform.services.hax.type }}
  selector:
    cortx.io/hax-enabled: "true"
  ports:
    - name: hax-tcp
      protocol: TCP
      port: {{ .Values.platform.services.hax.port }}
      targetPort: hax
{{- end }}
