apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortx.hare.hax.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "cortx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "cortx.selectorLabels" . | nindent 4 }}
    cortx.io/hax-enabled: "true"
  ports:
    - name: hax-http
      protocol: TCP
      port: {{ .Values.hare.hax.ports.http.port | int }}
      targetPort: hax-http
