apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortx.hare.hax.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "cortx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.platform.services.hax.type }}
  selector:
    cortx.io/hax-enabled: "true"
  ports:
    - name: hax-tcp
      protocol: TCP
      port: {{ .Values.platform.services.hax.port | int }}
      targetPort: hax
