{{- if .Values.rbacRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbacRole.name}}
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ .Values.podSecurityPolicy.name }}
{{- end }}