apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.io.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.services.io.type }}
  selector:
    cortx.io/service-type: "cortx-server"
  ports:
    - name: http-port80
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: https-port443
      protocol: TCP
      port: 443
      targetPort: 8443
    - name: port28049
      protocol: TCP
      port: 28049
      targetPort: 28049
