{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
##TODO Add any necessary secrets or imagePullSecrets referenced
##in values.yaml
##secrets:
## -TBD
##imagePullSecrets:
## -TBD
{{- end }}
