apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.io.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.services.io.type }}
  selector:
    cortx.io/service-type: "cortx-server"
  ports:
    - name: cortx-rgw-http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: cortx-rgw-https
      protocol: TCP
      port: 8443
      targetPort: 8443
