{{- if .Values.services.create -}}
{{- $svc := .Values.services.io -}}
{{- if gt (int $svc.count) 0 -}}
{{- $isLB := eq $svc.type "LoadBalancer" -}}
{{- $nodePortAllowed := or (eq $svc.type "NodePort") $isLB -}}
{{- $svcCount := ternary $svc.count 1 $isLB | int -}}
{{- $root := . -}}
{{- range $i := until $svcCount -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%d" $svc.name $i | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ $svc.type }}
  selector:
    cortx.io/service-type: "cortx-server"
  ports:
    - name: cortx-rgw-http
      protocol: TCP
      port: {{ $svc.ports.http }}
      targetPort: rgw-http
      {{- if and $nodePortAllowed (not (empty $svc.nodePorts.http)) }}
      nodePort: {{ add $svc.nodePorts.http $i }}
      {{- end }}
    - name: cortx-rgw-https
      protocol: TCP
      port: {{ $svc.ports.https }}
      targetPort: rgw-https
      {{- if and $nodePortAllowed (not (empty $svc.nodePorts.https)) }}
      nodePort: {{ add $svc.nodePorts.https $i }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
