apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxha.service.headless.name }}
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ .Values.cortxha.name }}