apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.cortxha.name }}
  name: {{ .Values.cortxha.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cortxha.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cortxha.name }}
        {{- if .Values.cortxha.machineid.value }}
        cortx.io/machine-id: {{ .Values.cortxha.machineid.value }}
        {{- end }}
        name: cortx-ha
        cortx.io/service-type: cortx-ha
    spec:
      hostname: {{ .Values.cortxha.service.headless.name }}
      serviceAccountName: {{ .Values.cortxha.serviceaccountname }}
      automountServiceAccountToken: true
      volumes:
        - name: {{ .Values.cortxha.cfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxha.cfgmap.name }}
        - name: {{ .Values.cortxha.sslcfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxha.sslcfgmap.name }}
        - name: {{ .Values.cortxha.machineid.volmountname }}
          configMap:
            name: {{ .Values.cortxha.machineid.name }}
        {{- if .Values.cortxha.machineid.value }}
        - name: machine-id
          downwardAPI:
            items:
              - path: "id"
                fieldRef:
                  fieldPath: metadata.labels['cortx.io/machine-id']
        {{- end }}
        - name: local-path-pv
          persistentVolumeClaim:
            claimName: {{ .Values.cortxha.localpathpvc.name }}
        {{- range .Files.Lines .Values.cortxha.secretinfo }}
        - name: {{ printf "%s" . }}
          secret:
            secretName: {{ printf "%s" . }}
        {{- end }}
      initContainers:
      - name: cortx-setup
        image: {{ .Values.cortxha.image }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
        {{- if eq .Values.cortxha.image  "ghcr.io/seagate/centos:7" }}
        args:
          - -c
          - sleep $(shuf -i 5-10 -n 1)s
        {{- else }}
        args:
          - -c
          {{- if .Values.cortxha.machineid.value }}
          - /opt/seagate/cortx/provisioner/bin/cortx_deploy -n $MACHINE_ID -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf
          {{- else }}
          - /opt/seagate/cortx/provisioner/bin/cortx_deploy -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf
          {{- end }}
        {{- end }}
        volumeMounts:
          - name: {{ .Values.cortxha.cfgmap.volmountname }}
            mountPath: {{ .Values.cortxha.cfgmap.mountpath }}
          - name: {{ .Values.cortxha.sslcfgmap.volmountname }}
            mountPath: {{ .Values.cortxha.sslcfgmap.mountpath }}
          {{- if .Values.cortxha.machineid.value }}
          - name: machine-id
            mountPath: {{ .Values.cortxha.machineid.mountpath }}
          {{- end }}
          - name: local-path-pv
            mountPath: {{ .Values.cortxha.localpathpvc.mountpath }}
          {{- range .Files.Lines .Values.cortxha.secretinfo }}
          - name: {{ printf "%s" . }}
            mountPath: /etc/cortx/solution/secret
            readOnly: true
          {{- end }}
        env:
          - name: MACHINE_ID            
            value: {{ printf "%s" .Values.cortxha.machineid.value | quote }}
        ports:
        - containerPort: 5050
        resources:
          requests:
            cpu: {{ .Values.cortxha.resource_allocation.setup.resources.requests.cpu }}
            memory: {{ .Values.cortxha.resource_allocation.setup.resources.requests.memory }}
          limits:
            cpu: {{ .Values.cortxha.resource_allocation.setup.resources.limits.cpu }}
            memory: {{ .Values.cortxha.resource_allocation.setup.resources.limits.memory }}
      containers:
        - name: cortx-ha-fault-tolerance
          image: {{ .Values.cortxha.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxha.image  "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command:
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/ha/bin/ha_start -s fault_tolerance -c yaml:///etc/cortx/cluster.conf
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxha.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxha.cfgmap.mountpath }}
            - name: {{ .Values.cortxha.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxha.sslcfgmap.mountpath }}
            {{- if .Values.cortxha.machineid.value }}
            - name: machine-id
              mountPath: {{ .Values.cortxha.machineid.mountpath }}
            {{- end }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxha.localpathpvc.mountpath }}
            {{- range .Files.Lines .Values.cortxha.secretinfo }}
            - name: {{ printf "%s" . }}
              mountPath: /etc/cortx/solution/secret
              readOnly: true
            {{- end }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxha.name }}
          resources:
            requests:
              cpu: {{ .Values.cortxha.resource_allocation.ha_fault_tolerance.resources.requests.cpu }}
              memory: {{ .Values.cortxha.resource_allocation.ha_fault_tolerance.resources.requests.memory }}
            limits:
              cpu: {{ .Values.cortxha.resource_allocation.ha_fault_tolerance.resources.limits.cpu }}
              memory: {{ .Values.cortxha.resource_allocation.ha_fault_tolerance.resources.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: false
        - name: cortx-ha-health-monitor
          image: {{ .Values.cortxha.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxha.image  "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command:
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/ha/bin/ha_start -s health_monitor -c yaml:///etc/cortx/cluster.conf
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxha.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxha.cfgmap.mountpath }}
            - name: {{ .Values.cortxha.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxha.sslcfgmap.mountpath }}
            {{- if .Values.cortxha.machineid.value }}
            - name: machine-id
              mountPath: {{ .Values.cortxha.machineid.mountpath }}
            {{- end }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxha.localpathpvc.mountpath }}
            {{- range .Files.Lines .Values.cortxha.secretinfo }}
            - name: {{ printf "%s" . }}
              mountPath: /etc/cortx/solution/secret
              readOnly: true
            {{- end }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxha.name }}
          resources:
            requests:
              cpu: {{ .Values.cortxha.resource_allocation.ha_health_monitor.resources.requests.cpu }}
              memory: {{ .Values.cortxha.resource_allocation.ha_health_monitor.resources.requests.memory }}
            limits:
              cpu: {{ .Values.cortxha.resource_allocation.ha_health_monitor.resources.limits.cpu }}
              memory: {{ .Values.cortxha.resource_allocation.ha_health_monitor.resources.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: false
        - name: cortx-ha-k8s-monitor
          image: {{ .Values.cortxha.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxha.image  "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command:
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/ha/bin/ha_start -s k8s_monitor -c yaml:///etc/cortx/cluster.conf
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxha.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxha.cfgmap.mountpath }}
            - name: {{ .Values.cortxha.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxha.sslcfgmap.mountpath }}
            {{- if .Values.cortxha.machineid.value }}
            - name: machine-id
              mountPath: {{ .Values.cortxha.machineid.mountpath }}
            {{- end }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxha.localpathpvc.mountpath }}
            {{- range .Files.Lines .Values.cortxha.secretinfo }}
            - name: {{ printf "%s" . }}
              mountPath: /etc/cortx/solution/secret
              readOnly: true
            {{- end }}
          env:
            - name: UDS_CLOUD_CONTAINER_NAME
              value: {{ .Values.cortxha.name }}
          resources:
            requests:
              cpu: {{ .Values.cortxha.resource_allocation.ha_k8s_monitor.resources.requests.cpu }}
              memory: {{ .Values.cortxha.resource_allocation.ha_k8s_monitor.resources.requests.memory }}
            limits:
              cpu: {{ .Values.cortxha.resource_allocation.ha_k8s_monitor.resources.limits.cpu }}
              memory: {{ .Values.cortxha.resource_allocation.ha_k8s_monitor.resources.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: false
