apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  labels:
    name: openldap-connect
spec:
  serviceName: {{ .Values.openldap.servicename }}
  replicas: {{ .Values.openldap.numreplicas }}
  selector:
    matchLabels:
      name: openldap-connect
  template:
    metadata:
      labels:
        name: openldap-connect
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
                matchLabels:
                  name: openldap-connect
      containers:
        - name: openldap
          image: {{ .Values.openldap.image }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: etc-3rd-party
              mountPath: /etc/3rd-party
            - name: var-data-3rd-party
              mountPath: /var/data/3rd-party
            - name: var-log-3rd-party
              mountPath: /var/log/3rd-party
          ports:
            - name: ldapport
              containerPort: 389
          command:
            - "/opt/entrypoint.sh"
          args:
            - "--rootdnpassword"
            - {{ .Values.openldap.password }}
            - --log_dir
            - /var/log/3rd-party
          resources:
            requests:
              memory: {{ .Values.openldap.resources.requests.memory }}
              cpu: {{ .Values.openldap.resources.requests.cpu }}
            limits:
              memory: {{ .Values.openldap.resources.limits.memory }}
              cpu: {{ .Values.openldap.resources.limits.cpu }}
  volumeClaimTemplates:
  - metadata:
      name: etc-3rd-party
    spec:
      storageClassName: {{ .Values.openldap.storageclass }}
      accessModes:
      - ReadWriteMany
      volumeMode: Filesystem
      resources:
        requests:
          storage: {{ $.Values.openldap.storagesize }}
  - metadata:
      name: var-data-3rd-party
    spec:
      accessModes:
      - ReadWriteMany
      volumeMode: Filesystem
      resources:
        requests:
          storage: {{ $.Values.openldap.storagesize }}
  - metadata:
      name: var-log-3rd-party
    spec:
      accessModes:
      - ReadWriteMany
      volumeMode: Filesystem
      resources:
        requests:
          storage: {{ $.Values.openldap.storagesize }}