apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openldap.servicename }}
spec:
  selector:
    name: openldap-connect
  ports:
    - name: port389
      protocol: TCP
      port: 389
      targetPort: 389