{{- range $line := .Files.Lines .Values.openldap.nodelistinfo }}
{{ $parts := split " " . }}
{{- $index := $parts._0 }}
{{- $nodename := $parts._1 }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "etc-3rd-party-%s" $index }}
spec:
  storageClassName: {{ $.Values.openldap.storageclass }}
  capacity:
    storage: {{ $.Values.openldap.storagesize }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ printf "etc-3rd-party-openldap-%s" $index }}
  local:
    path: /etc/3rd-party
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ printf "%s" $nodename }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "var-data-3rd-party-%s" $index }}
spec:
  storageClassName: {{ $.Values.openldap.storageclass }}
  capacity:
    storage: {{ $.Values.openldap.storagesize }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ printf "var-data-3rd-party-openldap-%s" $index }}
  local:
    path: /var/data/3rd-party
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ printf "%s" $nodename }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "var-log-3rd-party-%s" $index }}
spec:
  storageClassName: {{ $.Values.openldap.storageclass }}
  capacity:
    storage: {{ $.Values.openldap.storagesize }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ printf "var-log-3rd-party-openldap-%s" $index }}
  local:
    path: /var/log/3rd-party
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ printf "%s" $nodename }}
---
{{- end }}
