# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: integration
helm-extra-args: "--timeout 600s"
chart-dirs:
  - charts
excluded-charts:
chart-repos:
  - hashicorp=https://helm.releases.hashicorp.com
  - bitnami=https://charts.bitnami.com/bitnami
validate-chart-schema: false
check-version-increment: false
