# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: integration
lint-conf: .github/linters/lintconf.yaml
chart-yaml-schema: .github/linters/chart_schema.yaml
helm-extra-args: "--timeout 600s"
chart-dirs:
  - charts
excluded-charts:
chart-repos:
  - hashicorp=https://helm.releases.hashicorp.com
  - bitnami=https://charts.bitnami.com/bitnami
check-version-increment: false
all: true
