# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: integration
helm-extra-args: "--timeout 600s"
chart-dirs:
  - charts
excluded-charts:
chart-repos:
validate-chart-schema: false
