apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortx.configmapName" . }}
  labels: {{- include "cortx.labels" . | nindent 4 }}
data:
  cluster.yaml: |-
{{ include "cluster.yaml" . | indent 4 }}
  config.yaml: |-
{{ include "config.yaml" . | indent 4 }}
