{{- if .Values.waitForBackends.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortx.configmapName" . }}-scripts
  labels: {{- include "cortx.labels" . | nindent 4 }}
data:
  {{- $consulFullname := include "cortx.consul.fullname" . }}
  {{- $kafkaFullname := include "cortx.kafka.fullname" . }}
  {{- $releaseNamespace := .Release.Namespace }}
  wait-for-backends.sh: |
    #!/bin/bash

    set -o errexit
    set -o pipefail
    set -o nounset

    # Auxiliary functions
    k8s_wait_for_statefulset() {
        namespace=${1:?namespace is missing}
        statefulset=${2:?statefulset name is missing}
        local -i return_code=0

        echo "Waiting for statefulset ${statefulset} to be successfully rolled out..."
        kubectl rollout status --namespace "$namespace" statefulset "$statefulset" || return_code=$?
        echo "Rollout exit code: '${return_code}'"
        return $return_code
    }
    {{- if .Values.consul.enabled }}
    k8s_wait_for_statefulset {{ $releaseNamespace }} {{ $consulFullname }}-server
    {{- end }}
    {{- if .Values.kafka.enabled }}
    k8s_wait_for_statefulset {{ $releaseNamespace }} {{ $kafkaFullname }}
    {{- end }}
{{- end }}
