apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-ssl-cert" ((include "cortx.fullname" .) | trunc 54 ) }}
  labels: {{- include "cortx.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "ssl-cert/*").AsConfig | indent 2 }}
