apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortx.tls.configmapName" . }}
  labels: {{- include "cortx.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "ssl-cert/*").AsConfig | indent 2 }}
