{{- if not .Values.existingCertificateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortx.tls.secretName" . }}
  labels: {{- include "cortx.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "ssl-cert/*").AsSecrets | indent 2 }}
{{- end }}
