clusterdomain: cluster.local
cortxserver:
  serviceType: cortx-server
  image: ghcr.io/seagate/centos:7
  replicas: 3
  secretname: cortx-secret
  serviceaccountname: cortx
  rgw:
    resources:
      requests:
        memory: 128Mi
        cpu:    250m
      limits:
        memory: 2Gi
        cpu:    2000m
  hax:
    port: 22003
    resources:
      requests:
        memory: 128Mi
        cpu:    250m
      limits:
        memory: 2Gi
        cpu:    1000m
  service:
    clusterip:
      name: cortx-server-clusterip-svc
    headless:
      name: cortx-server-headless
  cfgmap:
    mountpath: /etc/cortx/solution
    volmountname: config001
    name: cortx
  sslcfgmap:
    mountpath: /etc/cortx/solution/ssl
    volmountname: ssl-config001
    name: cortx-ssl-cert
  localpathpvc:
    mountpath: /etc/cortx # This is the mount path in the container
    requeststoragesize: 1Gi
    storageclass: local-path
    accessmodes:
      - ReadWriteOnce
