cortxha:
  name: cortx-ha
  image: ghcr.io/seagate/centos:7
  secretinfo: secret-info.txt
  serviceaccountname: ha-monitor
  fault_tolerance:
    resources:
      requests:
        memory: 128Mi
        cpu:    250m
      limits:
        memory: 1Gi
        cpu:    500m
  health_monitor:
    resources:
      requests:
        memory: 128Mi
        cpu:    250m
      limits:
        memory: 1Gi
        cpu:    500m
  k8s_monitor:
    resources:
      requests:
        memory: 128Mi
        cpu:    250m
      limits:
        memory: 1Gi
        cpu:    500m
  service:
    clusterip:
      name: cortx-ha-clusterip-svc
    headless:
      name: cortx-ha-headless-svc
    loadbal:
      name: cortx-ha-loadbal-svc
  cfgmap:
    mountpath: /etc/cortx/solution
    volmountname: config001
    name: cortx
  sslcfgmap:
    mountpath: /etc/cortx/solution/ssl
    volmountname: ssl-config001
    name: cortx-ssl-cert
  machineid:
    mountpath: /etc/cortx/solution/node
    volmountname: machine-id-config
    name:  cortx-ha-machine-id-cfgmap
    value: ""
  localpathpvc:
    name: cortx-fs-local-pvc
    mountpath: /etc/cortx # This is the mount path in the container
    requeststoragesize: 1Gi
