apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ .Values.cortxcontrolprov.name }}
  name: {{ .Values.cortxcontrolprov.name }}
  namespace: {{ .Values.namespace }}
spec:
  hostname: {{ .Values.cortxcontrolprov.service.headless.name }}
  volumes:
    - name: {{ .Values.cortxcontrolprov.cfgmap.volmountname }}
      configMap:
        name: {{ .Values.cortxcontrolprov.cfgmap.name }}
    - name: {{ .Values.cortxcontrolprov.sslcfgmap.volmountname }}
      configMap:
        name: {{ .Values.cortxcontrolprov.sslcfgmap.name }}
    - name: {{ .Values.cortxcontrolprov.machineid.volmountname }}
      configMap:
        name: {{ .Values.cortxcontrolprov.machineid.name }}
    - name: {{ .Values.cortxgluster.pv.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.cortxgluster.pvc.name }}
    - name: local-path-pv
      persistentVolumeClaim:
        claimName: {{ .Values.cortxcontrolprov.localpathpvc.name }}
    {{- range .Files.Lines .Values.cortxcontrolprov.secretinfo }}
    - name: {{ printf "%s" . }}
      secret:
        secretName: {{ printf "%s" . }}
    {{- end }}
  containers:
  - name: cortx-setup
    image: {{ .Values.cortxcontrolprov.image }}
    imagePullPolicy: IfNotPresent        
    command: 
      - /bin/sh
    args: 
      - -c
      - /opt/seagate/cortx/provisioner/bin/cortx_deploy -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf ;
    volumeMounts:
      - name: {{ .Values.cortxcontrolprov.cfgmap.volmountname }}
        mountPath: {{ .Values.cortxcontrolprov.cfgmap.mountpath }}
      - name: {{ .Values.cortxcontrolprov.sslcfgmap.volmountname }}
        mountPath: {{ .Values.cortxcontrolprov.sslcfgmap.mountpath }}
      - name: {{ .Values.cortxcontrolprov.machineid.volmountname }}
        mountPath: {{ .Values.cortxcontrolprov.machineid.mountpath }}
      - name: {{ .Values.cortxgluster.pv.name }}
        mountPath: {{ .Values.cortxgluster.pv.mountpath }}
      - name: local-path-pv
        mountPath: {{ .Values.cortxcontrolprov.localpathpvc.mountpath }}
      {{- range .Files.Lines .Values.cortxcontrolprov.secretinfo }}
      - name: {{ printf "%s" . }}
        mountPath: /etc/cortx/solution/secret
        readOnly: true
      {{- end }}
    ports:
    - containerPort: 5050
  restartPolicy: Never