apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ .Values.cortxdataprov.name }}
  name: {{ .Values.cortxdataprov.name }}
  namespace: {{ .Values.namespace }}
spec:
  hostname: {{ .Values.cortxdataprov.service.headless.name }}
  volumes:
    - name: {{ .Values.cortxdataprov.cfgmap.volmountname }}
      configMap:
        name: {{ .Values.cortxdataprov.cfgmap.name }}
    - name: {{ .Values.cortxdataprov.sslcfgmap.volmountname }}
      configMap:
        name: {{ .Values.cortxdataprov.sslcfgmap.name }}
    - name: {{ .Values.cortxdataprov.machineid.volmountname }}
      configMap:
        name: {{ .Values.cortxdataprov.machineid.name }}
    {{- $nodename := (.Values.cortxdataprov.nodename) }}
    {{- range .Files.Lines .Values.cortxdataprov.mountblkinfo }}
    {{- $basepath := (base .) }}
    - name: {{ printf "cortx-data-%s-pv-%s" $basepath $nodename }}
      persistentVolumeClaim:
        claimName: {{ printf "cortx-data-%s-pvc-%s" $basepath $nodename }}
    {{- end }}
    - name: {{ .Values.cortxgluster.pv.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.cortxgluster.pvc.name }}
    - name: local-path-pv
      persistentVolumeClaim:
        claimName: {{ .Values.cortxdataprov.localpathpvc.name }}
    {{- range .Files.Lines .Values.cortxdataprov.secretinfo }}
    - name: {{ printf "%s" . }}
      secret:
        secretName: {{ printf "%s" . }}
    {{- end }}
  containers:
  - name: cortx-setup
    image: {{ .Values.cortxdataprov.image }}
    imagePullPolicy: IfNotPresent        
    command: 
      - /bin/sh
    {{- if eq .Values.cortxdataprov.image  "centos:7" }}
    args: 
      - -c
      - sleep $(shuf -i 5-10 -n 1)s
    {{- else }}
    args: 
      - -c
      - /opt/seagate/cortx/provisioner/bin/cortx_deploy -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf ;
    {{- end }}
    volumeDevices:
      {{- range .Files.Lines .Values.cortxdataprov.mountblkinfo }}
      - name: {{ printf "cortx-data-%s-pv-%s" ( base .) $nodename }}
        devicePath: {{ . }}
      {{- end }}
    volumeMounts:
      - name: {{ .Values.cortxdataprov.cfgmap.volmountname }}
        mountPath: {{ .Values.cortxdataprov.cfgmap.mountpath }}
      - name: {{ .Values.cortxdataprov.sslcfgmap.volmountname }}
        mountPath: {{ .Values.cortxdataprov.sslcfgmap.mountpath }}
      - name: {{ .Values.cortxdataprov.machineid.volmountname }}
        mountPath: {{ .Values.cortxdataprov.machineid.mountpath }}
      - name: {{ .Values.cortxgluster.pv.name }}
        mountPath: {{ .Values.cortxgluster.pv.mountpath }}
      - name: local-path-pv
        mountPath: {{ .Values.cortxdataprov.localpathpvc.mountpath }}
      {{- range .Files.Lines .Values.cortxdataprov.secretinfo }}
      - name: {{ printf "%s" . }}
        mountPath: /etc/cortx/solution/secret
        readOnly: true
      {{- end }}
    ports:
    - containerPort: 5050
  restartPolicy: Never
