# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

name: Lint

on:
  push:
    branches:
     - integration
     - main
  pull_request: ~

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.0

      - name: Run codespell
        uses: codespell-project/actions-codespell@v1.0  # TODO: replace with Seagate fork
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_file: .codespellignore
          skip: ./k8_cortx_cloud/templates/cloudformation/cloudformation.py

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.0

      - name: Run Shellcheck
        uses: Seagate/action-shellcheck@203a3fd018dfe73f8ae7e3aa8da2c149a5f41c33

  solution_yaml:
    name: Solution YAML validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.0

      - name: Validate solution.example.yaml
        run: ./solution_validation_scripts/solution-validation.sh solution.example.yaml
        shell: bash
        working-directory: ./k8_cortx_cloud

  # Reference: https://github.com/helm/chart-testing-action
  chart-lint-test:
    name: Lint and Test Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: Seagate/setup-helm@v2.1
        with:
          version: v3.8.2

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: Seagate/chart-testing-action@v2.2.1
        with:
          version: v3.5.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/linters/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/ct.yaml

      - name: Install helm-docs
        run: |
          wget -O /tmp/helm-docs.deb https://github.com/norwoodj/helm-docs/releases/download/v1.9.1/helm-docs_1.9.1_Linux_x86_64.deb
          sudo dpkg -i /tmp/helm-docs.deb

      - name: Check Docs
        run: |
          helm-docs --chart-search-root=charts
          if ! git diff --exit-code; then
            echo -e "\n\nChart documentation is not up to date. Please run helm-docs to update the chart README.md files and commit the updates."
            exit 1
          fi
