apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.cortxblkdata.storageClassName }}
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
