apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxserver.service.headless.name }}
  labels:
    cortx.io/service-type: {{ .Values.cortxserver.serviceType }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ .Values.cortxserver.name }}
    cortx.io/service-type:  {{ .Values.cortxserver.serviceType }}
    cortx.io/hax-enabled: "true"
    cortx.io/service-domain: "{{ .Values.cortxserver.service.headless.name }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterdomain }}"
---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.cortxserver.name }}
    cortx.io/service-type:  {{ .Values.cortxserver.serviceType }}
  name: {{ .Values.cortxserver.name }}
spec:
  podManagementPolicy: Parallel
  serviceName: {{ .Values.cortxserver.service.headless.name }}
  replicas: {{ .Values.cortxserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.cortxserver.name }}
      cortx.io/service-type: cortx-server
      cortx.io/hax-enabled: "true"
      cortx.io/service-domain: "{{ .Values.cortxserver.service.headless.name }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterdomain }}"
  template:
    metadata:
      labels:
        app: {{ .Values.cortxserver.name }}
        ### TODO CORTX-28968 k8s Label 'name: cortx-server' is deprecated in favor of 'cortx.io/service-type: cortx-server'
        name: cortx-server
        cortx.io/service-type: cortx-server
        cortx.io/hax-enabled: "true"
        cortx.io/service-domain: "{{ .Values.cortxserver.service.headless.name }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterdomain }}"
    spec:
      subdomain: {{ .Values.cortxserver.service.headless.name }}
      ### Avoid using below if possible due to limitations around Linux kernel field length limitations
      ### See https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field
      setHostnameAsFQDN: true
      serviceAccountName: {{ .Values.cortxserver.serviceaccountname }}
      volumes:
        - name: {{ .Values.cortxserver.cfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxserver.cfgmap.name }}
        - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxserver.sslcfgmap.name }}
        - name: machine-id
          emptyDir: {}
        - name: {{ .Values.cortxserver.secretname }}
          secret:
            secretName: {{ .Values.cortxserver.secretname }}
      initContainers:
      - name: cortx-setup
        image: {{ .Values.cortxserver.image }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
        args:
          {{- if eq .Values.cortxserver.image "ghcr.io/seagate/centos:7" }}
          - sleep $(shuf -i 5-10 -n 1)s
          {{- else }}
          - export MACHINE_ID=$(hostname --fqdn);
            export HOSTNAME=$(hostname);
            export MACHINE_ID=$(echo -n ${HOSTNAME} | md5sum | awk '{print $1}');
            echo "Storing MACHINE_ID of '${MACHINE_ID}' in '${MACHINE_ID_PATH}'.";
            echo "${MACHINE_ID}" > ${MACHINE_ID_PATH};
            /opt/seagate/cortx/provisioner/bin/cortx_deploy -n ${MACHINE_ID} -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf;
            sleep 10s;
          {{- end }}
          ### TODO CORTX-28968 Remove sleep from initContainer
        volumeMounts:
          - name: {{ .Values.cortxserver.cfgmap.volmountname }}
            mountPath: {{ .Values.cortxserver.cfgmap.mountpath }}
          - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
            mountPath: {{ .Values.cortxserver.sslcfgmap.mountpath }}
          - name: machine-id
            mountPath: {{ .Values.cortxserver.machineid.mountpath }}
          - name: local-path
            mountPath: {{ .Values.cortxserver.localpathpvc.mountpath }}
          - name: {{ .Values.cortxserver.secretname }}
            mountPath: /etc/cortx/solution/secret
            readOnly: true
        env:
          - name: MACHINE_ID_PATH
            value: "{{ .Values.cortxserver.machineid.mountpath }}/id"
        ports:
        - containerPort: 5050
      containers:
        - name: cortx-rgw
          image: {{ .Values.cortxserver.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxserver.image  "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command:
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/rgw/bin/rgw_setup start -c yaml:///etc/cortx/cluster.conf;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxserver.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.cfgmap.mountpath }}
            - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.sslcfgmap.mountpath }}
            - name: machine-id
              mountPath: {{ .Values.cortxserver.machineid.mountpath }}
            - name: local-path
              mountPath: {{ .Values.cortxserver.localpathpvc.mountpath }}
          ports:
          - name: rgw-http
            containerPort: 22751
            protocol: TCP
          - name: rgw-https
            containerPort: 23001
            protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
        - name: cortx-hax
          image: {{ .Values.cortxserver.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxserver.image  "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command:
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/hare/bin/hare_setup start --config yaml:///etc/cortx/cluster.conf;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxserver.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.cfgmap.mountpath }}
            - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.sslcfgmap.mountpath }}
            - name: machine-id
              mountPath: {{ .Values.cortxserver.machineid.mountpath }}
            - name: local-path
              mountPath: {{ .Values.cortxserver.localpathpvc.mountpath }}
          ports:
          - name: hax
            containerPort: {{ .Values.cortxserver.hax.port | int }}
            protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
  volumeClaimTemplates:
  - metadata:
      ### TODO CORTX-28968 Evaluate volumeClaimTemplate versus emptyDir
      name: local-path
    spec:
      accessModes: {{- toYaml .Values.cortxserver.localpathpvc.accessmodes | nindent 6 }}
      storageClassName: {{ .Values.cortxserver.localpathpvc.storageclass }}
      resources:
        requests:
          storage: {{ .Values.cortxserver.localpathpvc.requeststoragesize }}
